# -*- coding: utf-8 -*-
"""ml models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0vSaj0_JWHn4KVzrJliZNMCmHjAjZfl
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print('module install successfully!!!...')

path = 'filtered_customer_data.csv'
df = pd.read_csv(path)
df.head(10)

X = df[['total_purchases']]
y = df['total_spent']

X, y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_test, y_train, y_test

print(f"Traning data shape: {X_train.shape}, {y_train.shape}")
print(f"Testing data shape: {X_test.shape}, {y_test.shape}")

lr = LinearRegression()

lr.fit(X_train, y_train)

print(f"Intercept: {lr.intercept_}")
print(f"Coefficient: {lr.coef_}")

y_pread = lr.predict(X_test)
y_pread

mae = mean_absolute_error(y_test, y_pread)
mse = mean_squared_error(y_test, y_pread)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pread)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared Score: {r2:.2f}")

pread = lr.predict([[15]])
print(f'{pread[0]:.2f}')

pread1 = lr.predict(X.iloc[[0]])

pread1